varsion: '2'

services:
  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  oauth:
    image: tomcat:8.5.13-alpine
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./oauth:/usr/local/tomcat/webapps:Z
    depends_on:
      - mysql
    extra_hosts:
      - "database_server:127.0.0.1"